postgres:
  image: postgres:9.1
  environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sebastiangraf/gitlab:latest
  links:
    - redis:redisio
    - postgres:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - DB_USER=postgres
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  image: redis:latest